name: Deploy

on:
  push:

jobs:
  deploy:
    name: Deploy with CDK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install NPM packages
      run: npm install

    - name: Review Cloud Formation
      run: npx cdk synth

    - name: Review Incoming Changes
      run: npx cdk diff
    
    - name: Deploy
      run: npx cdk deploy
      if: ${{ github.ref == 'refs/head/main' }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install NPM packages
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Check formatting
      run: npm run prettier-check


    
          